// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xzyjabkwjstduvabbznj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6eWphYmt3anN0ZHV2YWJiem5qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2ODA4MTQsImV4cCI6MjA2NTI1NjgxNH0.OvSyNQF4FCHLMi1VJvAuKPJpcr6zKRpNB7jRRodpBwU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);